
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hhe80
 */
public class Room extends javax.swing.JFrame {

    /**
     * Creates new form Room
     */
    public Room() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Room_type = new javax.swing.JTextField();
        Room_No = new javax.swing.JTextField();
        Room_status1 = new javax.swing.JTextField();
        Room_Add = new javax.swing.JButton();
        Room_Data_Update = new javax.swing.JButton();
        Room_Data_Delete = new javax.swing.JButton();
        Room_Table_Show = new javax.swing.JButton();
        Room_back4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        Room_Charge = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Room_Type");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Room_No");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Status");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Room");

        Room_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_NoActionPerformed(evt);
            }
        });

        Room_status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_status1ActionPerformed(evt);
            }
        });

        Room_Add.setText("Add");
        Room_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_AddActionPerformed(evt);
            }
        });

        Room_Data_Update.setText("Update");
        Room_Data_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_Data_UpdateActionPerformed(evt);
            }
        });

        Room_Data_Delete.setText("Delete");
        Room_Data_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_Data_DeleteActionPerformed(evt);
            }
        });

        Room_Table_Show.setText("Show_Table");
        Room_Table_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_Table_ShowActionPerformed(evt);
            }
        });

        Room_back4.setText("Back");
        Room_back4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_back4ActionPerformed(evt);
            }
        });

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room_No", "Room-Type", "Status", "Room_Charge"
            }
        ));
        jScrollPane1.setViewportView(jTable10);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Room_Charge");

        Room_Charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_ChargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(188, 188, 188)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel21)
                                    .addGap(89, 89, 89))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Room_type, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Room_status1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(Room_No, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Room_Charge, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Room_Table_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_back4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_Data_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_Data_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel20)
                    .addContainerGap(514, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Room_back4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Room_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_No, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room_Data_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_type, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room_Data_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_status1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room_Table_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Room_Charge, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jLabel20)
                    .addContainerGap(622, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Room_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_NoActionPerformed

    private void Room_status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_status1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_status1ActionPerformed

    private void Room_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_AddActionPerformed
        // TODO add your handling code here:
        
              String Room_Id = Room_No.getText();
              String Room_Type = Room_type.getText();
              String Room_Status = Room_status1.getText();
              String Room_charge = Room_Charge.getText();
              
                 
                 
               try {
              
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
   
   
         
             
       String  sqlquery = "INSERT INTO Room(Room_No,Room_Type,Room_Status,Room_Charge) VALUES ('"+Room_Id+"','"+Room_Type+"','"+Room_Status +"','"+Room_charge+"')";
         
         PreparedStatement pst = connection.prepareStatement(sqlquery);
        
         pst.execute();
         JOptionPane.showMessageDialog(null, "Registration Complete");
        
      
        
         
        
       ////////////////Clear The Text Field
       
        Room_No.setText("");
        Room_type.setText("");
        Room_status1.setText("");
        Room_Charge.setText("");
        
       
       
         // this.hide();
       // new login().show();     
             
       
        } catch (Exception e) {
            e.printStackTrace();
        }  
                     
              
             
        
        
        
    }//GEN-LAST:event_Room_AddActionPerformed

    private void Room_Data_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_Data_UpdateActionPerformed
        // TODO add your handling code here:
        
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
            int row = jTable10.getSelectedRow();
            String value = (jTable10.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE Room SET Room_Type =?,Room_Status =?,Room_Charge=? WHERE Room_No  =" + value;
            PreparedStatement ps = connection.prepareStatement(sql);

            
            ps.setString(1, Room_type.getText());
            ps.setString(2, Room_status1.getText());
             ps.setString(3, Room_Charge.getText());
           
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) jTable10.getModel();
            model.setRowCount(0);
            
            JOptionPane.showMessageDialog(null, "UPDATE Complete");
        } catch (Exception e) {
            e.printStackTrace();
        }


                    
        Room_No.setText("");
        Room_type.setText("");
        Room_status1.setText("");
        Room_Charge.setText("");
        
        
    }//GEN-LAST:event_Room_Data_UpdateActionPerformed

    private void Room_Data_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_Data_DeleteActionPerformed
        // TODO add your handling code here:
        
        
         try {
              
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
            int row = jTable10.getSelectedRow();
            String value = (jTable10.getModel().getValueAt(row, 0).toString());
            String  sql = "DELETE FROM Room WHERE Room_No ="+value;
            PreparedStatement ps = connection.prepareStatement(sql);
        
         ps.executeUpdate();
          DefaultTableModel model = (DefaultTableModel)jTable10.getModel();
          model.setRowCount(0);
         JOptionPane.showMessageDialog(null, "DELETE Complete");
            } catch (Exception e) {
            e.printStackTrace();
        } 
        
        
    }//GEN-LAST:event_Room_Data_DeleteActionPerformed

    private void Room_Table_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_Table_ShowActionPerformed
        // TODO add your handling code here:
        
        
        try{

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");

            Statement st = connection.createStatement();
            String sql = "select *from Room";

            ResultSet rs = st.executeQuery(sql);

            while(rs.next()){

              String Room_Id = String.valueOf(rs.getString("Room_No"));
              String Room_Type = String.valueOf(rs.getString("Room_Type"));
              String Room_Status = String.valueOf(rs.getString("Room_Status"));
              String Room_Charge = String.valueOf(rs.getString("Room_Charge"));
              

                String tbData[] = {Room_Id ,Room_Type,Room_Status,Room_Charge};

                DefaultTableModel tblModel = (DefaultTableModel)jTable10.getModel();

                tblModel.addRow(tbData);

            }

        } catch (Exception e) {

            e.printStackTrace();

        }

            
        
    }//GEN-LAST:event_Room_Table_ShowActionPerformed

    private void Room_back4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_back4ActionPerformed
        // TODO add your handling code here:
        
        this.hide();
        new Admin().show();
    }//GEN-LAST:event_Room_back4ActionPerformed

    private void Room_ChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_ChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_ChargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Room_Add;
    private javax.swing.JTextField Room_Charge;
    private javax.swing.JButton Room_Data_Delete;
    private javax.swing.JButton Room_Data_Update;
    private javax.swing.JTextField Room_No;
    private javax.swing.JButton Room_Table_Show;
    private javax.swing.JButton Room_back4;
    private javax.swing.JTextField Room_status1;
    private javax.swing.JTextField Room_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable10;
    // End of variables declaration//GEN-END:variables
}
